# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quizdb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Ganesh}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# LOGGING (optional)
# ===============================
logging.level.org.springframework=INFO